### ISSUE TITLE
Feature작업엔 어떤 코드를 넣으면 되죠?

### ISSUE THREAD

**Issue by logichoon-redo** [Object-Study-Matching/iOS#3]
## Description

깃허브의 Issue나, Feature에 대한 질문을 남겨주세요.

Feature작업엔 어떤 코드를 넣으면 되죠?

**Comment by SHcommit** [comment]
여기 링크를 첨부했습니다. (<a href="https://github.com/IF-TG/iOS/pull/14">링크</a>) 여기 아래 내리면 [Feat] ,[Style] 등 있는데 주로 화면의 기능( 로그인 기능, 채팅, 홈 화면의 네비게이션바, cell 구현 등등) 화면이나 서버에서의 요청, 응답 기능 등을 Feat 작업으로 분류하면 좋을거 같아요.

Fix는 기존에 작업했던 코드를 고칠 경우,

Hotfix는 master에 올라가 있던 코드나 파일을 긴급하게 수정해야 할 경우 

Style은 이미지 리소스, 폰트 등을 추가한 경우

Refactor 는 코드 리펙터링을 진행한 경우로 분류하면 좋을거 같아요.

오른쪽 메뉴에 Label 보면 자신이 커밋해서 pull request하기까지 수행한 작업들을 한눈에 확인 가능하도록 관련된 레이블들을 체크해주세요 :)
