### ISSUE TITLE
폴더 이름을 구별해야하지 않을까요?

### ISSUE THREAD

**Issue by logichoon-redo** [Object-Study-Matching/iOS#5]
폴더이름 앞에 해당 페이지의 이름과 함께 작성하여 구별하는게 어떨까요?             

_Originally posted by @logicHoon-bit in https://github.com/Object-Study-Matching/iOS/pull/4#pullrequestreview-1459950764_

**Comment by SHcommit** [comment]
![11](https://github.com/Object-Study-Matching/iOS/assets/96910404/35eb93a0-7680-4ca7-9d42-966cf2650b7a)
![22](https://github.com/Object-Study-Matching/iOS/assets/96910404/deeb517a-998c-46f7-b911-07f8d2325f0c)

이런 Directory structure로 하는 것이 좋은 것 같습니다!!
